site_name: ExpanseMC
theme:
  name: 'readthedocs'
nav:
  - Home: 'index.md'
  - Players:
    - Magic: 'players/magic.md'
    - Ranks:
      - Donation: 'players/ranks/donation.md'
      - Money: 'players/ranks/money.md'
      - Player Kills: 'players/ranks/playerkills.md'
      - Play Time: 'players/ranks/playtime.md'
    - Towny: 'players/towny.md'
  - About:
    - 'Rules and Regulations': 'about/rules.md'
    - Staff: 'about/staff.md'